travis:
  secure:
    BINSTAR_TOKEN: LrpOwkrHt8VoLYlQYeebLMgOzNTMcpZmGzBZ/Jfx4xS1O0rltI+ALKSwII0MrUHhLs3CK0DNTWMgpjvBINbg09v8kzU/lZ0nS4UNr6VtB+iG0sPgQGxbcUgBd/kN6BEHQP7Gj8yuoitC+DtcaL0lK3Z09jFxwvIHdpH66IsCY2ZEmsLJ6W6YESRZGsssAWwjOGCl1UHIFp+rmTiLMB7BTfiziI+W7UzyuyXP85E3QooO6f80Lfv4N5VNCF18vShFKA7EPbxeTr6TiCaJIVtDSszbsE/Q8e/rOzSqLg95owKGmidBSLJP0KsguWtf+G+RqZyHSsxf6YL6gD+9bouEY/Zjj4tXlAhYB/ZO/g4/UQWemz+vYCORUocndw14+VLylDj5W/0g4ANkWYS7sr+oYHEzYyHkMCbpWTZy6/BrsoGqu9i+etrFmpVAanu8qnQyE6Wi7qsaPGN7LQ+uaIPfuHghNt84BVmHu6TZQykiQRcx+t/Og8dAhuP83GzIw1HElzy8jPhye7dlBKRqm1uzZAZeBGlpCxevsDVWsyz5lo5UPmX2zB1PjHyljhH57LSa7oyC+HXUT1z8n3ecunC7Rr+XpI6glWizQksdIOh8tN3fAweLlK30eudr/5qNTPddXuKwjq+JekD+tLnJv7uH9swAQX4h4tJaJa5Hu6+pXdA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
